Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |db|
    db.vm.box = "spox/ubuntu-arm"
    db.vm.box_version = "1.0.0"
    db.vm.provider :vmware_desktop do |vmware|
      vmware.gui = false
      vmware.cpus = 1
      vmware.ssh_info_public = true
      vmware.linked_clone = false
    end
  end
  config.vm.define "vm2" do |app|
    app.vm.box = "spox/ubuntu-arm"
    app.vm.box_version = "1.0.0"
    app.vm.provider :vmware_desktop do |vmware|
      vmware.gui = false
      vmware.cpus = 1
      vmware.ssh_info_public = true
      vmware.linked_clone = false
    end
  end
end