- name: Install Docker
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    name: docker.io

- name: Pull image
  community.docker.docker_image:
    name: mysql
    source: pull

- name: Run nginx
  community.docker.docker_container:
    name: mysqlDB
    image: mysql
    state: started
    auto_remove: yes
    detach: yes
    ports:
      - "3306:3306"
    env: 
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "{{ mysql_random_root_password }}"
