---

- name: Install logstash
  ansible.builtin.apt:
    name: logstash
    state: present

- name: Configure logstash
  ansible.builtin.template:
    src: beats.conf.j2
    dest: /etc/logstash/conf.d/beats.conf
    mode: 0644

- name: Enable and start logstash
  ansible.builtin.systemd:
    name: logstash
    state: started
    enabled: yes
