- name: Install jenkins
  hosts: servers
  become: true
  vars:
    java: "openjdk-11-jdk"
    jenkins_repo_url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install gnupg
      apt:
        name: gnupg
        state: present

    - name: Add Jenkins APT keyring
      shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc"
      args:
        executable: /bin/bash

    - name: Add Jenkins APT repository
      shell: sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      args:
        executable: /bin/bash

    - name: Install Java
      apt:
        name: default-jre
        state: present

    - name: Install Java
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Update package cache
      apt:
        update_cache: yes
        
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Retrieve initialAdminPassword file
      fetch:
        src: /var/lib/jenkins/secrets/initialAdminPassword
        dest: "{{ playbook_dir }}/initialAdminPassword"
        flat: yes

    - name: Print initialAdminPassword
      debug:
        msg: "Your initialAdminPassword is {{ lookup('file', '{{ playbook_dir }}/initialAdminPassword') }}"
        
    # - name: Download Jenkins repo key
    # #   apt_key:
    # #     url: "{{ jenkins_repo_url }}"
    # #     dest: /usr/share/keyrings/jenkins-keyring.asc
    # #     state: present
    #   become: true
    #   ansible.builtin.get_url:
    #     url: "{{ jenkins_repo_url }}"
    #     dest: /usr/share/keyrings/jenkins-keyring.asc
    # - name: Ensure the repository is configured
    #   apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
    #   become: true
    # - name: Update all packages to their latest version
    #   apt:
    #     # force_apt_get: yes
    #     # force: yes
    #     update_cache: yes
    #     upgrade: full
    #     state: latest
    #   # become: true
    # - name: Install Java
    #   apt:
    #     name: "{{ java }}"
    #     state: present
    #   # become: true
    # - name: Install Jenkins
    #   apt:
    #     name: jenkins
    #     state: present
    #   # become: true
    # - name: Start Jenkins
    #   service:
    #     name: jenkins
    #     state: started
    #     enabled: yes
    #   # become: true









    # - name: Update all packages to their latest version
    #   apt:
    #     upgrade: full
    # - name: download jenkins key
    #   ansible.builtin.get_url:
    #     url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    #     dest: /usr/share/keyrings/jenkins-keyring.asc
    # - name: Add Jenkins repo
    #   ansible.builtin.apt_repository:
    #     repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    #     state: present
    #     filename: jenkins.list  




    # - name: Update all packages to their latest version
    #   apt:
    #     name: "*"
    #     state: latest
    # - name: download jenkins key
    #   ansible.builtin.get_url:
    #     url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    #     dest: /usr/share/keyrings/jenkins-keyring.asc
    # - name: Add Jenkins repo
    #   ansible.builtin.apt_repository:
    #     repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    #     state: present
    #     filename: jenkins.list  
    # - name: Update all packages to their latest version
    #   apt:
    #     name: "*"
    #     state: latest
    # - name: Install the Jenkins
    #   ansible.builtin.apt:
    #     name: jenkins
    #     state: latest  
    # - name: Make sure a service unit is running
    #   ansible.builtin.systemd:
    #     state: started
    #     name: jenkins
    #     enabled: yes