apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: c3ltYm9s
  MYSQL_USER: c3ltYm9s
  MYSQL_PASSWORD: c3ltYm9s
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_HOST: c3ltYm9sLWRi
  DB_USER: c3ltYm9s
  DB_PASSWORD: c3ltYm9s
  DB_NAME: c3ltYm9s