Vagrant.configure("2") do |config|
  # config.vm.define "vm1" do |app|
  #   app.vm.box = "spox/ubuntu-arm"
  #   app.vm.box_version = "1.0.0"
  #   app.vm.provision "shell", path: "universal.sh", args: [ "ufw", "apache2", "docker.io", "mariadb-server"]
  #   app.vm.provider :vmware_desktop do |vmware|
  #     vmware.gui = false
  #     vmware.cpus = 1
  #     vmware.ssh_info_public = true
  #     vmware.linked_clone = false
  #   end
  # end
  config.vm.define "vm2" do |app|
    app.vm.box = "gyptazy/centos9-arm64"
    app.vm.box_version = "1.0.0"
    app.vm.provision "shell", path: "universal.sh", args: [ "httpd", "firewalld", "docker", "MariaDB-server"]
    app.vm.provider :vmware_desktop do |vmware|
      vmware.gui = false
      vmware.cpus = 1
      vmware.ssh_info_public = true
      vmware.linked_clone = false
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
    end
  end
  config.vm.define "vm3" do |app|
    app.vm.box = "gyptazy/fedora38-arm64"
    app.vm.box_version = "1.0.0"
    app.vm.provision "shell", path: "universal.sh", args: [ "httpd", "firewalld", "docker", "MariaDB-server"]
    app.vm.provider :vmware_desktop do |vmware|
      vmware.gui = false
      vmware.cpus = 1
      vmware.ssh_info_public = true
      vmware.linked_clone = false
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
    end
  end
end